version: "3"
services:
  server:
    image: part4:check
    container_name: server
    tty: true
    user: root

  part_6:
    image: nginx:latest
    ports:
     - 80:8080
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: part_6
    tty: true
